version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker_svtr
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sistema_votacao_tempo_real_database
    volumes:
      - sistema_votacao_tempo_real_pg_data:/bitnami/postgresql

  regis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - sistema_votacao_tempo_real_regis_data:/bitnami/redis

volumes:
  sistema_votacao_tempo_real_pg_data:
  sistema_votacao_tempo_real_regis_data:
